### ISSUE TITLE
Feil på 2c. 

### ISSUE THREAD

**Issue by steffenbs** [bcwein/R-Code-UiS#2]
https://github.com/bcwein/R-Code-UiS/blob/c631407b63151f135ef817bb22bfdbce1e576cc3/Exercise/Exercise-set-2.Rmd#L109

lambda = 20 eller 10? for 10 år

**Comment by bcwein** [comment]
Takk for tilbakemelding! Setter pris på det.

Likevel:
Lambda = 20. Siden Poisson(2) over 10 år kan modelleres som Poisson(2*10) = Poisson(20). 
Lukker issuen.
